---
# FASTQ file or folder containing FASTQ files
input_fastq: "data/hg002_simple_test_chr12_44420446_44421533/"
# FASTA file containing the reference genome
reference_fasta: "data/test_reference/human_g1k_v37_part.fasta"
# Minimum SV length
min_sv_length: 30
# Maximum SV length
max_sv_length: 100000
# Min read length. Shorter reads will be discarded
min_read_length: 1000
# Min mapping quality. Reads will lower mapping quality will be discarded
min_read_mapping_quality: 20
# Minimum read support required to call a SV (auto for auto-detect)
min_read_support: 'auto'
# Sample name
sample_name: "sv_sample01"

# (optional) Threads
# default is a max of 30
# threads: 30

# (optional) BED file containing targeted regions. SVs will only be called in
# regions contained in the BED file
# target_bed : "data/test_reference/test_target.bed"
